import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAllTables1760000000000 implements MigrationInterface {
  name = "CreateAllTables1760000000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TYPE "trainer_gender_enum" AS ENUM ('Male', 'Female', 'Other')
    `);

    await queryRunner.query(`
      CREATE TYPE "player_gender_enum" AS ENUM ('Male', 'Female', 'Other')
    `);

    await queryRunner.query(`
      CREATE TYPE "squad_player_position_enum" AS ENUM ('Goalkeeper', 'Defender', 'Midfielder', 'Striker', 'Backup')
    `);

    await queryRunner.query(`
      CREATE TABLE "trainer" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "firstName" varchar(255) NOT NULL,
        "lastName" varchar(255) NOT NULL,
        "gender" "trainer_gender_enum" NOT NULL
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "player" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "firstName" varchar(255) NOT NULL,
        "lastName" varchar(255) NOT NULL,
        "gender" "player_gender_enum" NOT NULL
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "squad" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" varchar(255) NOT NULL,
        "description" varchar(255) NOT NULL,
        "date" timestamp NOT NULL
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "squad_player" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "position" "squad_player_position_enum" NOT NULL,
        "playerId" integer NOT NULL,
        "squadId" integer NOT NULL,
        CONSTRAINT "FK_b30bce6da6a7af3ec6166d94a8c"
          FOREIGN KEY ("playerId") REFERENCES "player"("id")
          ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "FK_7b057c95526d65d6e6aad55b64e"
          FOREIGN KEY ("squadId") REFERENCES "squad"("id")
          ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "squad_trainer" (
        "squadId" integer NOT NULL,
        "trainerId" integer NOT NULL,
        CONSTRAINT "PK_squad_trainer" PRIMARY KEY ("squadId", "trainerId"),
        CONSTRAINT "FK_2eed9d9322ea09ac6e70e8eb6fd"
          FOREIGN KEY ("squadId") REFERENCES "squad"("id")
          ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "FK_f468b71f8ccc0bb36243a8adc07"
          FOREIGN KEY ("trainerId") REFERENCES "trainer"("id")
          ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_2eed9d9322ea09ac6e70e8eb6f"
      ON "squad_trainer" ("squadId")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_f468b71f8ccc0bb36243a8adc0"
      ON "squad_trainer" ("trainerId")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "IDX_f468b71f8ccc0bb36243a8adc0"`);
    await queryRunner.query(`DROP INDEX "IDX_2eed9d9322ea09ac6e70e8eb6f"`);

    await queryRunner.query(`DROP TABLE "squad_trainer"`);
    await queryRunner.query(`DROP TABLE "squad_player"`);
    await queryRunner.query(`DROP TABLE "squad"`);
    await queryRunner.query(`DROP TABLE "player"`);
    await queryRunner.query(`DROP TABLE "trainer"`);

    await queryRunner.query(`DROP TYPE "squad_player_position_enum"`);
    await queryRunner.query(`DROP TYPE "player_gender_enum"`);
    await queryRunner.query(`DROP TYPE "trainer_gender_enum"`);
  }
}
