import { MigrationInterface, QueryRunner } from "typeorm";

export class SeedSquadPlayer1764671658933 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO "squad_player" ("playerId", "squadId", "position") VALUES
        (1, 1, 'Goalkeeper'),
        (2, 1, 'Defender'),
        (3, 1, 'Defender'),
        (4, 1, 'Midfielder'),
        (5, 1, 'Midfielder'),
        (6, 1, 'Midfielder'),
        (7, 1, 'Striker'),
        (8, 1, 'Backup'),
        (9, 2, 'Goalkeeper'),
        (10, 2, 'Defender'),
        (11, 2, 'Defender'),
        (12, 2, 'Midfielder'),
        (13, 2, 'Midfielder'),
        (14, 2, 'Midfielder'),
        (15, 2, 'Striker'),
        (16, 2, 'Backup'),
        (17, 3, 'Goalkeeper'),
        (18, 3, 'Defender'),
        (19, 3, 'Defender'),
        (20, 3, 'Midfielder'),
        (21, 3, 'Midfielder'),
        (22, 3, 'Midfielder'),
        (23, 3, 'Striker'),
        (24, 3, 'Backup'),
        (25, 4, 'Goalkeeper'),
        (26, 4, 'Defender'),
        (27, 4, 'Defender'),
        (28, 4, 'Midfielder'),
        (29, 4, 'Midfielder'),
        (30, 4, 'Midfielder'),
        (31, 4, 'Striker'),
        (32, 4, 'Backup'),
        (33, 5, 'Goalkeeper'),
        (34, 5, 'Defender'),
        (35, 5, 'Defender'),
        (36, 5, 'Midfielder'),
        (37, 5, 'Midfielder'),
        (38, 5, 'Midfielder'),
        (39, 5, 'Striker'),
        (40, 5, 'Backup'),
        (41, 6, 'Goalkeeper'),
        (42, 6, 'Defender'),
        (43, 6, 'Defender'),
        (44, 6, 'Midfielder'),
        (45, 6, 'Midfielder'),
        (46, 6, 'Midfielder'),
        (47, 6, 'Striker'),
        (48, 6, 'Backup'),
        (49, 6, 'Backup'),
        (50, 6, 'Backup'),
        (1,  7, 'Goalkeeper'),
        (2,  7, 'Defender'),
        (3,  7, 'Defender'),
        (4,  7, 'Midfielder'),
        (5,  7, 'Midfielder'),
        (6,  7, 'Midfielder'),
        (7,  7, 'Striker'),
        (8,  7, 'Backup'),
        (9,  8, 'Goalkeeper'),
        (10, 8, 'Defender'),
        (11, 8, 'Defender'),
        (12, 8, 'Midfielder'),
        (13, 8, 'Midfielder'),
        (14, 8, 'Midfielder'),
        (15, 8, 'Striker'),
        (16, 8, 'Backup'),
        (17, 9, 'Goalkeeper'),
        (18, 9, 'Defender'),
        (19, 9, 'Defender'),
        (20, 9, 'Midfielder'),
        (21, 9, 'Midfielder'),
        (22, 9, 'Midfielder'),
        (23, 9, 'Striker'),
        (24, 9, 'Backup'),
        (25, 10, 'Goalkeeper'),
        (26, 10, 'Defender'),
        (27, 10, 'Defender'),
        (28, 10, 'Midfielder'),
        (29, 10, 'Midfielder'),
        (30, 10, 'Midfielder'),
        (31, 10, 'Striker'),
        (32, 10, 'Backup'),
        (33, 11, 'Goalkeeper'),
        (34, 11, 'Defender'),
        (35, 11, 'Defender'),
        (36, 11, 'Midfielder'),
        (37, 11, 'Midfielder'),
        (38, 11, 'Midfielder'),
        (39, 11, 'Striker'),
        (40, 11, 'Backup'),
        (41, 12, 'Goalkeeper'),
        (42, 12, 'Defender'),
        (43, 12, 'Defender'),
        (44, 12, 'Midfielder'),
        (45, 12, 'Midfielder'),
        (46, 12, 'Midfielder'),
        (47, 12, 'Striker'),
        (48, 12, 'Backup'),
        (49, 12, 'Backup'),
        (50, 12, 'Backup')
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "squad_player"`);
  }
}
