
["(IPA)"]
"Arbeitsjournal führen" = [
  [
    "s",
    5,
    1,
  ],
  [
    "s",
    9,
    1,
  ],
  [
    "b",
    12,
    2,
  ],
  [
    "i",
    14,
    1,
  ],
  [
    "b",
    16,
    1,
  ],
  [
    "s",
    17,
    1,
  ],
  [
    "i",
    18,
    1,
  ],
  [
    "s",
    20,
    2,
  ],
  [
    "s",
    23,
    1,
  ],
  [
    "i",
    24,
    2,
  ],
  [
    "s",
    26,
    2,
  ],
  [
    "s",
    30,
    2,
  ],
  [
    "s",
    34,
    2,
  ],
  [
    "b",
    36,
    2,
  ],
]
Expertenbesuche = [["b", 11, 1]]

[Informieren]
"Informationen sammeln" = [["b", 0, 1]]

[Planen]
"Planen + ERD erstellen" = [["b", 1, 1]]

[Entscheiden]
"Lösungsvariante festlegen" = [["b", 2, 1]]

[Realisieren]
Entities = [["b", 3, 1]]
Requests = [["s", 4, 1], ["i", 6, 1]]
Services = [["s", 6, 1], ["i", 7, 1]]
Controllers = [["s", 7, 1], ["i", 8, 1], ["i", 21, 1]]
Relationen = [["s", 8, 1], ["i", 9, 2], ["i", 23, 1]]
Datenbank = [["i", 4, 1], ["s", 10, 1]]
Migrationen = [["i", 5, 1], ["s", 14, 1]]
Authentifizierung = [["b", 15, 1], ["i", 17, 1], ["s", 18, 1]]
Swagger = [["b", 19, 1], ["i", 20, 1], ["i", 22, 1]]

[Kontrollieren]
Fehlerbehebung = [["s", 22, 1], ["s", 28, 2], ["i", 31, 1], ["i", 33, 3]]
Testen = [["s", 24, 2], ["i", 26, 5], ["i", 32, 1]]

[Auswerten]
"Reflexion & Fazit" = [["s", 38, 1]]

["(Abschliessen)"]
"Dokumentation abschliesen" = [["s", 39, 1]]
Puffer = [["s", 32, 2]]
